#define ALIGNX "right"
#define ALIGNY "top"
#define HORZALIGN "user_right"
#define VERTALIGN "user_top"
#define FOREGROUND false
#define HIDEINMENU true
#define FONT "default"
#define FONTSCALE 1.3
#define T_X -15
#define X_INCREMENT -5
#define T_Y 20
#define Y_INCREMENT 15
#define COLOR_TOTAL RED
#define COLOR_CURRENT GREEN
#define TEXT ""